name: Update Submodule

on:
  push:
    branches:
      - main  # Adjust the branch name as needed
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight (UTC)

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: true  # This ensures submodules are also checked out

      - name: Update Submodule to Latest Commit
        run: |
          cd Guide  # Replace 'Guide' with your submodule path
          git checkout main  # Ensure you are on the correct branch
          git pull origin main  # Pull the latest changes
          cd ..
          git add Guide
          git commit -m "Auto-update submodule to the latest commit"
          git push origin main